### PR TITLE
Improvements to RPM installer

### PR DESCRIPTION
**Pull request by petebrew**

### CODE REVIEW

**Comment by petebrew** [comment]
Contains lots of work on the RPM install method and upgrades to dependencies where there are no problems.

**Comment by PaulBoon** [comment]
Having a problem building with mvn clean install:

Running nl.knaw.dans.dccd.rest.AbstractResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.751 sec <<< FAILURE!
initializationError(nl.knaw.dans.dccd.rest.AbstractResourceTest)  Time elapsed: 0.005 sec  <<< ERROR!
org.powermock.reflect.exceptions.FieldNotFoundException: Field 'fTestClass' was not found in class org.junit.internal.runners.MethodValidator.
    at org.powermock.reflect.internal.WhiteboxImpl.getInternalState(WhiteboxImpl.java:643)
...

**Comment by PaulBoon** [comment]
If I downgrade junit to version 4.11 build chokes with: 
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.3:rpm (generate-rpm) on project dccd-http: Source location src/main/assembly/dccd-rest.xml does not exist -> [Help 1]
 maybe you forgot to add that file.

**Comment by petebrew** [comment]
fTestClass error is an incompatibility problem between the JUnit version powermock uses and the JUnit version that was specified in the pom.  There is no need to include JUnit as a dependency in dccd-http when it's already a transient dependency through powermock.  Removing it from the pom has things working again (we're now using Junit 4.8.1 provided by Powermock).  But... you are right - I did forget to commit the dccd-rest.xml file.  Now done.

One remaining problem is that two of your unit tests are failing:
  authenticateSuccesfull(nl.knaw.dans.dccd.rest.AbstractResourceTest): nl.knaw.dans.dccd.application.services.DccdUserService is not an interface
  authenticateFail(nl.knaw.dans.dccd.rest.AbstractResourceTest): nl.knaw.dans.dccd.application.services.DccdUserService is not an interface

This seems to be something to do with easymock?  Can you check Paul?  With these two unit tests commented out, the build runs fine.

**Comment by PaulBoon** [comment]
just added the easymock dependency and then it builds.

```
<dependency>
        <groupId>org.easymock</groupId>
        <artifactId>easymock</artifactId>
        <version>3.4</version>
</dependency>
```

Need to test the service...

**Pull request merged**
